# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id_comment', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_author', models.BigIntegerField()),
                ('id_publication', models.BigIntegerField()),
                ('date', models.DateTimeField()),
                ('text', models.TextField()),
                ('addressee', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('height', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_author', models.BigIntegerField()),
                ('id_publication', models.BigIntegerField()),
                ('author_to', models.BigIntegerField()),
                ('type', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id_publication', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_author', models.BigIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('text', models.TextField()),
                ('theme', models.CharField(max_length=50)),
                ('html_page', models.FileField(upload_to='publications')),
                ('is_private', models.BooleanField()),
                ('is_public', models.BooleanField()),
                ('is_private_edit', models.BooleanField()),
                ('is_public_edit', models.BooleanField()),
                ('is_marks', models.BooleanField()),
                ('is_comments', models.BooleanField()),
                ('tags', models.TextField()),
                ('tree_path', models.TextField()),
                ('comments', models.BigIntegerField()),
                ('imports', models.BigIntegerField()),
                ('marks', models.BigIntegerField()),
                ('likes', models.BigIntegerField()),
                ('read', models.BigIntegerField()),
                ('edits', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_reg', models.BigIntegerField()),
                ('user_online', models.BigIntegerField()),
                ('publications_create', models.BigIntegerField()),
                ('publications_delete', models.BigIntegerField()),
                ('publications_active', models.BigIntegerField()),
                ('publications_private', models.BigIntegerField()),
                ('publications_public', models.BigIntegerField()),
                ('comments', models.BigIntegerField()),
                ('notifications', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('likes', models.BigIntegerField()),
                ('publications', models.BigIntegerField()),
                ('imports', models.BigIntegerField()),
                ('comments', models.BigIntegerField()),
                ('imports_it', models.BigIntegerField()),
                ('commented_it', models.BigIntegerField()),
                ('avatar', models.ImageField(upload_to='avatars')),
            ],
        ),
    ]
