# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='Statistics',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
