# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-03 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_statistics_users_total_reg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
