# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-17 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_auto_20160417_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_author', models.BigIntegerField()),
                ('nickname_author', models.CharField(max_length=100)),
                ('rating', models.BigIntegerField()),
                ('text', models.TextField()),
                ('data', models.DateField()),
                ('id_author_answer', models.BigIntegerField()),
                ('nickname_author_answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CommentBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_publication', models.BigIntegerField()),
                ('last_id', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.CommentBlock'),
        ),
    ]
