# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-17 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_auto_20160417_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='data',
            field=models.CharField(max_length=100),
        ),
    ]
