# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-17 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_auto_20160417_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='num_position',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
