# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-23 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0014_auto_20160423_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamiccommentparagraph',
            name='last_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
