# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-23 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0015_dynamiccommentparagraph_last_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.BigIntegerField()),
                ('nickname', models.BigIntegerField()),
                ('type', models.CharField(max_length=100)),
                ('id_publ_like', models.BigIntegerField(blank=True)),
                ('id_user_like', models.BigIntegerField(blank=True)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
