# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-23 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0016_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='nickname',
            field=models.CharField(max_length=100),
        ),
    ]
