# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-23 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0017_auto_20160423_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preview_publ_id',
            field=models.BigIntegerField(default=-1),
            preserve_default=False,
        ),
    ]
