# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-24 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0018_user_preview_publ_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.BigIntegerField()),
                ('nickname', models.CharField(max_length=100)),
                ('id_publ', models.BigIntegerField()),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
