# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-01 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0019_viewing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.BigIntegerField()),
                ('nickname_user', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.Publication')),
            ],
        ),
    ]
