# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-03 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0020_editor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_developer', models.IntegerField()),
                ('name_developer', models.TextField(max_length=100)),
            ],
        ),
    ]
