# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-09 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0021_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='html_page',
            field=models.TextField(),
        ),
    ]
