# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-13 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0022_auto_20160510_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_publ',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
