# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-15 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0023_user_saved_publ'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_author', models.BigIntegerField()),
                ('nickname_author', models.CharField(max_length=100)),
                ('name_author', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
    ]
