# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-16 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0024_bugreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colleague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_colleague', models.BigIntegerField()),
                ('is_favorit', models.BooleanField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.User')),
            ],
        ),
    ]
