# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-16 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0025_colleague'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colleague',
            old_name='is_favorit',
            new_name='is_favorite',
        ),
    ]
