# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-16 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0027_auto_20160516_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_author', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date', models.CharField(max_length=100)),
                ('is_read', models.BooleanField()),
                ('is_delete', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.User')),
            ],
        ),
    ]
