# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-23 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0028_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
