# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-23 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0029_notification_message_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='id_publication',
            field=models.BigIntegerField(default=-1),
            preserve_default=False,
        ),
    ]
