# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-17 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0031_auto_20160625_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_position', models.BigIntegerField()),
                ('id_author', models.BigIntegerField()),
                ('text', models.TextField()),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicParagraphs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_publication', models.BigIntegerField()),
                ('total_paragraphs', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='dynamiccomment',
            name='dynamic_paragraphs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.DynamicParagraphs'),
        ),
    ]
