# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-17 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0032_auto_20160717_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamiccomment',
            name='dynamic_paragraphs',
        ),
        migrations.DeleteModel(
            name='DynamicComment',
        ),
        migrations.DeleteModel(
            name='DynamicParagraphs',
        ),
    ]
