# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-17 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0033_auto_20160717_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_position', models.BigIntegerField()),
                ('id_author', models.BigIntegerField()),
                ('text', models.TextField()),
                ('rating', models.BigIntegerField()),
                ('date', models.CharField(max_length=100)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.Publication')),
            ],
        ),
    ]
