# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-22 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0034_dynamiccomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamiccomment',
            old_name='num_position',
            new_name='paragraph',
        ),
        migrations.AddField(
            model_name='dynamiccomment',
            name='position',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
