# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-24 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0035_auto_20160722_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='main_comments',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
