# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-24 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0036_publication_main_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comment', models.BigIntegerField()),
                ('id_author', models.BigIntegerField()),
                ('id_publication', models.BigIntegerField()),
                ('date', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_comments',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
