# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-25 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0037_auto_20160924_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='file_tree',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
