# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-25 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0038_user_file_tree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_folder', models.BigIntegerField()),
                ('id_author', models.BigIntegerField()),
                ('date', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_folders',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
