# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-07 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0040_publication_versions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='versions',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
