# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-01 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0043_auto_20161230_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colleague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.BigIntegerField()),
                ('id_colleague', models.BigIntegerField()),
            ],
        ),
    ]
