# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-01 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0044_colleague'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sender', models.BigIntegerField()),
                ('id_addressee', models.BigIntegerField()),
                ('is_read', models.BooleanField()),
                ('date', models.DateField()),
                ('html_text', models.TextField()),
            ],
        ),
    ]
