# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-01 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0046_notification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
