# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-01 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0047_auto_20170101_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='form', max_length=10),
            preserve_default=False,
        ),
    ]
