# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-01 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0048_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='id_notification',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
