# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-01 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0049_notification_id_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
