# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-01 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0050_auto_20170101_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='total_notification',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
