# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-03 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0052_publication_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tree',
        ),
    ]
