# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-04 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0053_remove_user_tree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamiccomment',
            old_name='text',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='dynamiccomment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='dynamiccomment',
            name='id_author',
        ),
        migrations.RemoveField(
            model_name='dynamiccomment',
            name='position',
        ),
        migrations.RemoveField(
            model_name='dynamiccomment',
            name='rating',
        ),
    ]
