# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-04 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0054_auto_20170104_1440'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DynamicComment',
            new_name='DynamicParagraph',
        ),
    ]
