# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-04 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0055_auto_20170104_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='total_dynamic_comments',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
