# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-14 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0060_commentrating_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrating',
            name='type',
            field=models.CharField(max_length=4),
        ),
    ]
