# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-15 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0062_commentrating_id_user_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_group', models.BigIntegerField()),
                ('id_author', models.BigIntegerField()),
                ('type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1500)),
                ('members', models.TextField()),
                ('date_create', models.CharField(max_length=100)),
                ('rating', models.BigIntegerField()),
                ('tags', models.TextField()),
            ],
        ),
    ]
