# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-15 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0064_group_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
