# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-21 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0065_group_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='preview_publ_id',
            field=models.BigIntegerField(blank=True, default=-1),
            preserve_default=False,
        ),
    ]
