# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-22 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0066_group_preview_publ_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_show_contents',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='is_show_date',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='is_show_description',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='is_show_members',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='is_show_preview_tree',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='is_show_rating',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='is_show_status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='is_show_tags',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='is_show_total_members',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='is_show_total_publ',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
