# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-22 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0068_auto_20170122_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_show_author',
            field=models.BooleanField(default=True),
        ),
    ]
