# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-22 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0069_group_is_show_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('to_id', models.BigIntegerField()),
                ('type', models.CharField(max_length=5)),
            ],
        ),
    ]
