# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-23 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0070_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_type',
            field=models.CharField(blank=True, default='msg', max_length=5),
        ),
    ]
