# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-11 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0071_auto_20170123_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=16)),
            ],
        ),
    ]
