# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-24 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0072_invitekeys'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BugReport',
        ),
        migrations.DeleteModel(
            name='Colleague',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentRating',
        ),
        migrations.RemoveField(
            model_name='dynamicparagraph',
            name='publication',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Starring',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Viewing',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='html_page',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='is_contents',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='is_files',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='is_general_comments',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='is_links',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='is_protected_edit',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='is_starring',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='is_versions',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='main_comments',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='stars',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='versions',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='total_comments',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='total_dynamic_comments',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='total_folders',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='total_notification',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='user_online',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notify_text',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notify_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='publications',
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='DynamicParagraph',
        ),
    ]
