# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-24 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0073_auto_20170724_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='total_folders',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
