# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-24 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0074_statistics_total_folders'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
