# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-24 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0075_registrationkeys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistrationKeys',
            new_name='RegistrationKey',
        ),
    ]
