# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-24 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0076_auto_20170724_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationkey',
            name='date',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
